(uiop/package:define-package :cldpf/item (:nicknames) (:use :cl) (:shadow)
                             (:export :item-list-template) (:intern))
(in-package :cldpf/item)
;;don't edit above

(defun item-list-template (&key length name url)
  (with-output-to-string (out)
    (format out "(:enclosure (:url ~S" (format nil "~Aaudios/~A.mp3" (with-/ url) name))
    (format out "~%             :type ~S" "audio/mpeg")
    (format out "~%             :length ~S)" (if length length ""))
    (format out "~% :title ~S" "")
    (format out "~% :description ~S" "")
    (format out "~% :pubdate ~S" "")
    (format out "~% :notes ()")
    (format out "~% :explicit nil)")))

(defun with-/ (url)
  (let ((last-char (elt url (1- (length url)))))
    (if (not (char= #\/ last-char))
        (format nil "~A~A" url #\/)
        url)))